# Copyright (C) 2023-2024  ANSSI
# SPDX-License-Identifier: CC0-1.0

baseURL: "https://n1NjaMonk3y.github.io"
title: n1NjaMoNk3y
defaultContentLanguage: "en"
publishDir: "docs"
pluralizelisttitles: false
capitalizeListTitles: false
disableKinds: ["taxonomy"]
ignoreErrors: ["error-disable-taxonomy"]

# Site Theme
theme: hackropole

# Removes non-spacing marks from composite characters in content paths
removePathAccents: true

# Enable generation of robots.txt file for web crawlers
enableRobotsTXT: true

# A challenge has one category but multiple tags
taxonomies:
  category: category
  fcsc: fcsc
  tags: tags

permalinks:
  tags: /:slug:/
  fcsc: /:slug:/

languages:
  en:
    languageCode: en
    languageName: English
    contentDir: "content/"
    params:
      description: Cybersecurity | Hacking | Technology
      # Homepage event banner
      homepageNoticeTitle: Write-Host "Welcome $message"
      homepageNoticeContent: Welcome to my site.
      # homepageNoticeCountdown: 1712322000000
    weight: 2

# Add JSON for search engine and remove RSS on homepage
outputs:
  home: ["HTML", "JSON"]

# Do not use inline styles for code highlighting (blocked by CSP header)
markup:
  highlight:
    noClasses: false
    style: solarized
