name: Build and Commit Hugo Site
on:
  push:
    branches: [main]
permissions:
  contents: write  # Grants write access to the repository
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true  # To handle themes/hackropole
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'  # Match your local Hugo version
      - name: Build
        run: hugo --minify
      - name: Commit Docs
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add docs/
          git diff --staged --quiet || git commit -m "Update docs folder with latest build"
          git push origin main